# -*- coding: utf-8 -*-
"""LVADSUSR152_POOJA GODULA_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ptGBwnP83obepR2uFpAMrlHmT9SlIFtY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#1a.Loading dataset
cricket_data=pd.read_csv('/content/Final Dataset - IPL.csv')
#1b
#number of rows and columns
rows,columns_=cricket_data.shape
print(rows)
print(columns_)
#data types of dataset
print('________')
print(cricket_data.dtypes)
#info
print('________')
print(cricket_data.info())

#2a.checking missing values and no missing values in the data
print(cricket_data.isnull().sum())
#2b.checking duplicates and no duplicates in the data
print(cricket_data.duplicated().sum())

cricket_data.head()

#3 statistics of data
df=pd.DataFrame(cricket_data,columns=['first_ings_score','first_ings_wkts','second_ings_score','second_ings_wkts','highscore'])
print(df.mean())
print(df.sum())
print(df.median())
print(df.mode())
print(df.std())
print(f'{df.min()}-{df.max()}')
print(df.var())

#4  matches winners
#BAR GRAPH
def bar_graph(cricket_data):
  cricket_data.groupby('match_winner').size().sort_values(ascending=False).plot(kind='bar',title='MATCH WINNERS')
  plt.figure(figsize=(8,9))
  return plt.show()
def histogram(cricket_data):
  cricket_data['first_ings_wkts'].plot(kind='hist', bins=10, title='first_ings_wkts',color='r')
  plt.title('WICKETS FALLING IN FIRST INNINGS')
  plt.legend()
  return plt.show()
def linechart(cricket_data):
  cricket_data['match_id'].plot(kind='line', figsize=(8, 4), title='match_id')
  return plt.show()

s=bar_graph(cricket_data)
h=histogram(cricket_data)
l=linechart(cricket_data)

#5 Correlation Matrix
plt.subplots(figsize=(8, 8))
d = pd.DataFrame({
    x_label: grp['toss_winner'].value_counts()
    for x_label, grp in cricket_data.groupby('match_winner')
})
sns.heatmap(d,annot=True)
plt.xlabel('match_winner')
plt.ylabel('toss-winner')
plt.title("CORRELATION BETWEEN MATCH WINNER AND TOSS WINNER")
plt.show()

#6
cricket_data.plot(kind='box', x='first_ings_score')
plt.xlabel("FIRST INNINGS score")
#plt.ylabel("FIRST INNINGS SCORE")
plt.title(" score analysis")
plt.legend()
plt.show()

#7 venue impact on the match winner in a stage
venue_match_win=cricket_data.groupby(['venue','stage'])['match_winner'].count().head(5).sort_values(ascending=False).plot(kind='bar')
plt.xlabel("VENUE AND STAGE")
plt.ylabel("MATCH WINNER COUNT")
plt.title("IMPACT OF VENUE ON THE MATCH WINNER TEAM IN A PARTICULAR STAGE")
plt.legend()
plt.show()
#venue_match_win

cricket_data.head()

#8
x=cricket_data['top_scorer'].head(10)
y=cricket_data['highscore'].head(10)
plt.bar(x,y)
plt.title("High Scores by players")
plt.xlabel('Cricketer')
plt.ylabel('high scores')
plt.show()

"""#9
ANALYSIS OF DATASET:
*   There are 74 rows and 20 columns.
*   Every column is either object or int data type.
*   There are no null values in the dataset
*   There are no duplicate values

Score Analysis:
*   score innings in the first innings are higher in their own venue
*   In 6th match more no of wickets fallen in the first innings
*   In second innings most of the times score is around 160
*   In second innings most of the wickets taken around the score 80


Venue and stage Analysis:

*   Most of the time finals happened in the narendra modi stadium ahmedabad gujarat
*   Most number of winning matches happened in the dy patil stadium mumbai in the stage matches


Toss and match win Analysis:

*   out of 7,4 times Banglore won the toss so most of the banglore won toss.
*   Rajasthan and Punjab won the matches twice when won the toss.







"""