# -*- coding: utf-8 -*-
"""lvadsusr152_Pooja_Godula_lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nnieJ5UZ-ykrYr2AVGyx68wu9L7ct5Y0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('penguins_classification.csv')

data.shape

data.head()

data.dtypes

data.isnull().sum()

data.duplicated().sum()

for i in data.select_dtypes(include='object'):
  plt.figure(figsize=(5,4))
  sns.countplot(data[i])
  plt.show()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in data.select_dtypes(include='object'):
  data[i]=le.fit_transform(data[i])
data.dtypes

data['species'].value_counts()

plt.figure(figsize=(10,5))
for i in data.columns:
  sns.boxplot(data[[i]])

sns.heatmap(data.corr(),annot=True,fmt='.2f')

data=data.drop(columns=['year'],axis=1)

x=data.drop(columns=['species'],axis=1)
y=data['species']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=2)
model.fit(x_train,y_train)
y_predict=model.predict(x_test)

from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,recall_score,precision_score,classification_report
print(f'accuracy of the model is {accuracy_score(y_predict,y_test)}')
print(f'precision of the model is {precision_score(y_predict,y_test)}')
print(f'recall of the model is {recall_score(y_predict,y_test)}')
print(f'f1_score of the model is {f1_score(y_predict,y_test)}')

sns.heatmap(confusion_matrix(y_predict,y_test),annot=True,fmt='.2f')

print(f'Classification report of the KNN Model is {classification_report(y_predict,y_test)}')