# -*- coding: utf-8 -*-
"""lvadsusr152_Pooja_Godula_lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108lzpo-WmYLM4v7QOYMBkBgbmL_Dc1_Q
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('Fare prediction.csv')

data.head()

data.shape

data.columns

data.info()

data.dtypes

data.isnull().sum()

data.duplicated().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in data.columns:
  data[i]=le.fit_transform(data[i])
data.dtypes

plt.figure(figsize=(15,5))
for i in data.columns:
  sns.boxplot(data[[i]])

d=data.corr()
d

sns.heatmap(data.corr(),annot=True,fmt='.2f'),

data['passenger_count'].value_counts()

x=data.drop(columns='passenger_count',axis=1)

y=data['passenger_count']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print(f'r2_score of {r2_score(y_pred,y_test)}')
print(f'mean_absolute_error of {mean_absolute_error(y_pred,y_test)}')
print(f'mean_squared_error of {mean_squared_error(y_pred,y_test)}')